apiVersion: v1
kind: Secret
metadata:
  name: dispatcher
  namespace: bots
type: Opaque
stringData:
  RABBITMQ_URL: amqp://guest:guest@rabbitmq.platform.svc.cluster.local:5672/
  DATABASE_URL: postgresql+asyncpg://ttt:ttt@postgres.platform.svc.cluster.local:5432/ttt
