"""add bot source column

Revision ID: 353c41ecc7b4
Revises: c19b6e2bf955
Create Date: 2026-06-03 16:54:54.706081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '353c41ecc7b4'
down_revision: Union[str, Sequence[str], None] = 'c19b6e2bf955'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('source', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bots', 'source')
    # ### end Alembic commands ###
