"""initial schema

Revision ID: c19b6e2bf955
Revises: 
Create Date: 2026-06-03 09:52:06.949070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c19b6e2bf955'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('base_name', sa.String(), nullable=False),
    sa.Column('versioned_name', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('owner_token', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('python_version', sa.String(), server_default='3', nullable=False),
    sa.Column('submitted_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('versioned_name')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bot_x_id', sa.Integer(), nullable=False),
    sa.Column('bot_o_id', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('played_at', sa.DateTime(), server_default=sa.text("(datetime('now'))"), nullable=False),
    sa.CheckConstraint("result IN ('x_wins', 'o_wins', 'cat', 'x_forfeit', 'o_forfeit')", name='ck_matches_result'),
    sa.ForeignKeyConstraint(['bot_o_id'], ['bots.id'], ),
    sa.ForeignKeyConstraint(['bot_x_id'], ['bots.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['bots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moves',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('move_number', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('board_state', sa.String(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moves')
    op.drop_table('matches')
    op.drop_table('bots')
    # ### end Alembic commands ###
