"""add pod_name and pod_ready to bots

Revision ID: e3991cfac58e
Revises: b4e7f2a91c8d
Create Date: 2026-06-11 22:36:34.140381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3991cfac58e'
down_revision: Union[str, Sequence[str], None] = 'b4e7f2a91c8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('pod_name', sa.String(), nullable=True))
    op.add_column('bots', sa.Column('pod_ready', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bots', 'pod_ready')
    op.drop_column('bots', 'pod_name')
    # ### end Alembic commands ###
