"""drop bot file_path column

Revision ID: f3af65520232
Revises: 353c41ecc7b4
Create Date: 2026-06-03 18:52:15.535580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3af65520232'
down_revision: Union[str, Sequence[str], None] = '353c41ecc7b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bots', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
