apiVersion: v1
kind: Secret
metadata:
  name: postgres
  namespace: platform
type: Opaque
stringData:
  POSTGRES_USER: ttt
  POSTGRES_PASSWORD: ttt
  POSTGRES_DB: ttt
  DATABASE_URL: postgresql+asyncpg://ttt:ttt@postgres-postgresql.platform.svc.cluster.local:5432/ttt
