apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  namespace: platform
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: guest
  RABBITMQ_DEFAULT_PASS: guest
  RABBITMQ_URL: amqp://guest:guest@rabbitmq.platform.svc.cluster.local:5672/
