apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - Namespace.yaml
  - secrets/postgres.yaml
  - secrets/rabbitmq.yaml
  - postgres/StatefulSet.yaml
  - postgres/Service.yaml
  - rabbitmq/Deployment.yaml
  - rabbitmq/Service.yaml
  - web/Deployment.yaml
  - web/Service.yaml
  - match-scheduler/Deployment.yaml
